### ISSUE TITLE
Add ma_target_ref_db_details.seq_db_sequence_version_date

### ISSUE THREAD

**Issue by bienchen** [ihmwg/python-modelcif#12]
In one of the meetings around ModelCIF or 3D-Beacons, the working groups agreed to keep the version of UniProtKB entries within the mmCIF file. This means we need the `ma_target_ref_db_details.seq_db_sequence_version_date` data item.

**Comment by benmwebb** [comment]
The Python equivalent would be a `datetime.date` object. Easy to generate the mmCIF by calling its `isoformat()` method.

**Comment by benmwebb** [comment]
Should be resolved by #15.
