### ISSUE TITLE
Multiline string for model details

### ISSUE THREAD

**Issue by gtauriello** [ihmwg/python-modelcif#27]
@benmwebb I noticed that the package can handle multiline strings in general but somehow when I try a multiline string for model_details I get a single line text with escaped '\n' characters.

In the attached zip file [here](https://github.com/ihmwg/python-modelcif/files/9213219/Archive.zip) you will find the following:
- mkmodbase-multiline.py to generate the multiline.cif file
- my expected output in multiline_exp.cif with an mmCIF-style multiline string

**Comment by gtauriello** [comment]
Actually the example was overly complicated and didn't showcase the issue when reading the file back in.

Here a better example:
[multiline-test.zip](https://github.com/ihmwg/python-modelcif/files/9213286/multiline-test.zip)

**Comment by benmwebb** [comment]
Yes, python-ihm only supports output of multiline strings within `loop_` constructs, and it doesn't use a loop for `_struct`. This is an oversight and should be easy to fix.

**Comment by brindakv** [comment]
@benmwebb `multi_line` strings should be allowed for `model_details` but `struct` should not be looped.

**Comment by benmwebb** [comment]
The fix does not loop `struct`.

**Comment by brindakv** [comment]
Ok thank you. Just wanted to make sure.
