### ISSUE TITLE
Support data_id for associated files

### ISSUE THREAD

**Issue by gtauriello** [ihmwg/python-modelcif#32]
Following up on the recent addition of the `data_id` field to `_ma_associated_archive_file_details` and `_ma_entry_associated_files` (see [commit](https://github.com/ihmwg/ModelCIF/commit/ff1d66506610375012ca8f466a32407f787d37d4) added to v1.4.4 of ModelCIF)...

I think one could have a function in `modelcif.associated.File` which enables an instance of `modelcif.data.Data` (or its subclasses) to be added to it and the dumper would then use this to assign a `data_id` in the appropriate table. Do you think this would work?

We have a few use cases in ModelArchive which could benefit from this and one of them is a conversion I am currently doing.

**Comment by benmwebb** [comment]
It'd be easy enough to have `File` and its subclasses take an optional `data` argument. I can take a look.
