### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by gtauriello** [ihmwg/python-modelcif#35]
Only today, I noticed that the recent changes in  #34 did not lead to a new release of python-modelcif. Was there a reason to avoid doing a new release? For our current efforts to improve ModelCIF support in SWISS-MODEL, it would be necessary to have the latest changes in a release since we have all our dependencies as software libraries with specific version numbers.

**Comment by benmwebb** [comment]
No problem, I can certainly make a new release.

**Comment by benmwebb** [comment]
Addressed by 1.0 release.
