### ISSUE TITLE
Support ma_template_non_poly

### ISSUE THREAD

**Issue by bienchen** [ihmwg/python-modelcif#5]
Soon I will need the `ma_template_non_poly` category for [TBvar3D](https://swissmodel.expasy.org/var3d/myctu/overview) models to be deposited in [ModelArchive]([www.modelarchive.org](http://www.modelarchive.org/)). There are some models that were actually docking experiments, so a non-polymer ligand serves as a template.

**Comment by benmwebb** [comment]
This *should* be straightforward. We already support adding `NonPolyChemComp` to `Entity`, and python-ihm outputs the various IHM non-poly tables, so we should be able to use similar logic to output the MA non-poly tables too.
